src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private ?string $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private ?string $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $isDone = false;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tasks" ,cascade={"persist"}, fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="assignedTasks", fetch="EAGER")
     */
    private $assignedTo;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $AssignedAt;

    public function __construct()
    {
        $this->createdAt = new \Datetime();
        $this->isDone = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIsDone(): ?bool
    {
        return $this->isDone;
    }

    public function setIsDone(bool $isDone): self
    {
        $this->isDone = $isDone;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function isDone()
    {
        return $this->isDone;
    }

    public function getAssignedTo(): ?User
    {
        return $this->assignedTo;
    }

    public function setAssignedTo(?User $AssignedTo): self
    {
        $this->assignedTo = $AssignedTo;

        return $this;
    }

    public function getAssignedAt(): ?\DateTimeInterface
    {
        return $this->AssignedAt;
    }

    public function setAssignedAt(?\DateTimeInterface $AssignedAt): self
    {
        $this->AssignedAt = $AssignedAt;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'title',
                TextType::class,
                [
                    'label' => 'Titre',
                ]
            )
            ->add(
                'content',
                TextareaType::class,
                ['label' => 'Contenu']
            )
            ->add(
                'assignedTo'
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Task::class,
            ]
        );
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Entity\User;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class TaskController
 *
 * @package App\Controller
 */
class TaskController extends AbstractController
{
    private const LIMIT = 6;
    private PaginatorInterface $paginator;

    private EntityManagerInterface $manager;

    /**
     * TaskController constructor.
     *
     * @param PaginatorInterface $paginator
     * @param EntityManagerInterface $manager
     */
    public function __construct(PaginatorInterface $paginator, EntityManagerInterface $manager)
    {
        $this->paginator = $paginator;
        $this->manager = $manager;
    }

    /**
     * @Route("/task/all", name="task_list")
     *
     * @param PaginatorInterface $paginator
     * @param TaskRepository $repo
     * @param Request $request
     * @return Response
     */
    public function indexAll(TaskRepository $repo, Request $request): Response
    {
        $tasks = $this->paginator->paginate(
            $repo->findAll(),
            $request->query->getInt('page', 1),
            self::LIMIT
        );

        return $this->render(
            'task/index.html.twig',
            [
                'controller_name' => 'TaskController',
                'tasks' => $tasks,
                'btn' => 'btnAll'
            ]
        );
    }

    /**
     * @Route("/task/todo", name="task_list_todo")
     *
     * @param TaskRepository $repo
     * @param Request $request
     * @return Response
     */
    public function indexTodo(TaskRepository $repo, Request $request): Response
    {
        $tasks = $this->paginator->paginate(
            $repo->findAllTodo(),
            $request->query->getInt('page', 1),
            self::LIMIT
        );

        return $this->render(
            'task/index.html.twig',
            [
                'controller_name' => 'TaskController',
                'tasks' => $tasks,
                'btn' => 'btnTodo'
            ]
        );
    }

    /**
     * @Route("/task/done", name="task_list_done")
     *
     * @param TaskRepository $repo
     * @param Request $request
     * @return Response
     */
    public function indexDone(TaskRepository $repo, Request $request): Response
    {
        $tasks = $this->paginator->paginate(
            $repo->findAllDone(),
            $request->query->getInt('page', 1),
            self::LIMIT
        );

        return $this->render(
            'task/index.html.twig',
            [
                'controller_name' => 'TaskController',
                'tasks' => $tasks,
                'btn' => 'btnDone'
            ]
        );
    }

    /**
     * @Route("/task/inprogress", name="task_list_progress")
     *
     * @param TaskRepository $repo
     * @param Request $request
     * @return Response
     */
    public function indexInProgress(TaskRepository $repo, Request $request): Response
    {
        $tasks = $this->paginator->paginate(
            $repo->findAllInProgress(),
            $request->query->getInt('page', 1),
            self::LIMIT
        );

        return $this->render(
            'task/index.html.twig',
            [
                'controller_name' => 'TaskController',
                'tasks' => $tasks,
                'btn' => 'btnInProgress'
            ]
        );
    }

    /**
     * @Route("/task/assign/{id}", name="task_assign", methods={"POST"})
     *
     * @param Task $task
     * @return JsonResponse
     */
    public function assignTask(Task $task): JsonResponse
    {
        $task->setAssignedTo($this->getUser())
            ->setAssignedAt(new \DateTime('NOW'));

        $this->manager->persist($task);
        $this->manager->flush();

        $this->addFlash('success', 'La tâche vous a été assigné.');

        return new JsonResponse(['success' => 1]);
    }


    /**
     * @Route("/tasks/create", name="task_create")
     *
     * @param Request $request
     * @return Response
     */
    public function createTask(Request $request): Response
    {
        $task = new Task();
        $user = $this->getUser();
        $task->setUser($user);

        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task->setUser($user);

            $this->manager->persist($task);
            $this->manager->flush();

            $this->addFlash('success', 'La tâche a été bien été ajoutée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/create.html.twig', ['form' => $form->createView()]);
    }


    /**
     * @Route("/tasks/{id}/edit", name="task_edit")
     *
     * @param Task $task
     * @param Request $request
     * @return Response
     */
    public function editTask(Task $task, Request $request): Response
    {
        if ($this->isGranted('edit', $task)) {
            $form = $this->createForm(TaskType::class, $task);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $this->manager->flush();

                $this->addFlash('success', 'La tâche a bien été modifiée.');

                return $this->redirectToRoute('task_list');
            }
            return $this->render(
                'task/edit.html.twig',
                [
                    'form' => $form->createView(),
                    'task' => $task,
                ]
            );
        }

        $this->addFlash('error', 'Vous n\'avez pas le droit d\'editer cette tâche.');

        return $this->redirectToRoute('task_list');
    }


    /**
     * @Route("/tasks/{id}/toggle", name="task_toggle")
     *
     * @param Task $task
     * @return Response
     */
    public function toggleTask(Task $task): Response
    {
        if ($this->isGranted('validate', $task)) {
            if ($task->isDone()) {
                $task->setIsDone(false)
                    ->setAssignedTo(null)
                    ->setAssignedAt(null);

                $this->addFlash('success', sprintf('La tâche %s a été réinitialisé.', $task->getTitle()));
            } else {
                $task->setIsDone(true);
                $this->addFlash('success', sprintf('La tâche %s a été marqué comme validé.', $task->getTitle()));
            }

            $this->manager->flush();

            return $this->redirectToRoute('task_list');
        }
        $this->addFlash('error', 'Vous n\'avez pas le droit de modifier cette tâche.');

        return $this->redirectToRoute('task_list');
    }

    /**
     * @Route("/tasks/{id}/delete", name="task_delete")
     */
    public function deleteTask(Task $task): Response
    {
        if ($this->isGranted('delete', $task)) {
            $this->manager->remove($task);
            $this->manager->flush();
            $this->addFlash('success', 'La tâche a bien été supprimée.');

            return $this->redirectToRoute('task_list');
        }

        $this->addFlash('error', 'Vous n\'avez pas le droit de supprimer cette tâche.');

        return $this->redirectToRoute('task_list');
    }
}

templates/task/_header.html.twig
<div class="container">
    <section class="jumbotron shadow text-center p-3 mt-5">
        <div class="container">
            <h1 class="jumbotron-heading">Todo List</h1>
            <p class="lead text-muted">Gérer vos tâches via l'application.</p>
        </div>
    </section>
</div>

templates/task/_modal.html.twig
<!-- line modal -->
<div class="modal fade modal-success" id="myModal{{ task.id }}" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="lineModalLabel">
                    {{ task.title }}
                    {% if task.isDone %}
                        <div class="badge bg-success ml-2">
                            Done
                        </div>
                    {% elseif task.assignedTo %}
                        <div class="badge bg-warning ml-2">
                            In progress
                        </div>

                    {% else %}
                        <div class="badge bg-danger ml-2">
                            Todo
                        </div>
                    {% endif %}

                    <div class="widget-subheading">
                        <label for="username">Créé par {{ task.user }}</label>
                    </div>
                    <div class="widget-assigned">
                        <b>assigné à :</b> {% if task.assignedto %}{{ task.assignedto }} {% else %}
                            <i>personne</i> {% endif %}
                    </div>
                </h3>
            </div>
            <div class="modal-body">

                <!-- content goes here -->
                <form>

                    <div class="form-group">
                        {{ task.content }}

                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <div class="btn-group btn-group-justified" role="group" aria-label="group button">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default" data-dismiss="modal" role="button">Fermer</button>
                    </div>
                    <div class="btn-group btn-delete hidden" role="group">
                        <a href="{{ path('task_edit', {'id' : task.id }) }}">
                            <button type="button" id="delImage" class="btn btn-default btn-hover-red" role="button">
                                Editer
                            </button>
                        </a>
                    </div>
                    <div class="btn-group" role="group">
                        <a href="{{ path('task_delete', {'id' : task.id }) }}">
                            <button type="button" id="saveImage" class="btn btn-default btn-hover-green"
                                    data-action="save" role="button">Supprimer
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/task/_task.html.twig
<div style="position: static;" class="ps ps--active-y">
    <div class="ps-content">
        <ul class=" list-group list-group-flush">
            {% for task in tasks %}
                {# load modal #}
                {{ include('task/_modal.html.twig') }}

                <li id="tasks" class="list-group-item">
                    {% if task.isDone %}
                        <div class="todo-indicator bg-success"></div>
                    {% elseif task.assignedTo %}
                        <div class="todo-indicator bg-warning"></div>
                    {% else %}
                        <div class="todo-indicator bg-danger"></div>
                    {% endif %}
                    <div class="widget-content p-0">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left ml-2">
                                <div class="widget-heading">
                                    <a data-toggle="modal" href="#myModal{{ task.id }}"><b>{{ task.title }}</b></a>
                                    {% if task.isDone %}
                                        <div class="badge bg-success ml-2">
                                            Done
                                        </div>
                                        <div class="widget-assigned">
                                            validé par : {{ task.assignedTo }}
                                        </div>
                                    {% elseif task.assignedTo %}
                                        <div class="badge bg-warning ml-2">
                                            In progress
                                        </div>
                                        <small><i class="far fa-clock"></i>
                                            depuis {{ date( task.assignedAt|date ).diff(date()).days }} jours</small>
                                        <div class="widget-assigned">
                                            assigné à : {{ task.assignedTo }}
                                        </div>
                                    {% else %}
                                        <div class="badge bg-danger ml-2">
                                            Todo
                                        </div>
                                        <div class="widget-assigned">
                                            assigné à : <i>personne</i>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="widget-subheading"><i>de {{ task.user }}
                                        le {{ task.createdAt|date("d/m/Y") }}</i></div>
                            </div>
                            <div class="widget-content-right">
                                {% if not task.assignedTo and not task.isDone %}
                                    <button class="assign border-0 btn-transition btn btn-outline-warning"
                                            data-toggle="tooltip" title="Assigner" data-id="{{ task.id }}">
                                        <i class="fas fa-people-arrows"></i>
                                    </button>
                                {% endif %}
                                {% if task.assignedTo  and not task.isDone %}
                                    <a href="{{ path('task_toggle', {'id' : task.id }) }}">
                                        <button class="border-0 btn-transition btn btn-outline-success"
                                                data-toggle="tooltip" title="Cloturer">
                                            <i class="fa fa-check"></i>
                                        </button>
                                    </a>
                                {% endif %}
                                {% if task.isDone %}
                                    <a href="{{ path('task_toggle', {'id' : task.id }) }}">
                                        <button class="border-0 btn-transition btn btn-outline-danger"
                                                data-toggle="tooltip" title="Réouvrir">
                                            <i class="fas fa-times-circle"></i>
                                        </button>
                                    </a>
                                {% endif %}
                                <a href="{{ path('task_edit', {'id' : task.id }) }}">
                                    <button class="edit border-0 btn-transition btn btn-outline"
                                            data-toggle="tooltip" title="Editer" data-id="{{ task.id }}">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                </a>
                                <a href="{{ path('task_delete', {'id' : task.id }) }}">
                                    <button class="border-0 btn-transition btn btn-outline-danger" data-toggle="tooltip"
                                            title="Supprimer">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/task/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">

        <section class="jumbotron shadow-lg p-3 m-5">
            <h2 class="jumbotron-heading text-center">Ajouter une tâche</h2>
        {{ form_start(form, {'action' : path('task_create')}) }}
        {{ form_widget(form) }}

        <button type="submit" class="btn btn-success pull-right">Ajouter</button>
        {{ form_end(form) }}

        <a href="{{ path('task_list') }}" class="btn btn-primary">Retour à la liste des tâches</a>
        </section>
    </div>

{% endblock %}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <section class="jumbotron shadow-lg p-3 m-5">
            <h2 class="jumbotron-heading text-center">Éditer une tâche</h2>
            {{ form_start(form, {'action' : path('task_edit', { 'id' : task.id })}) }}
            {{ form_row(form.title) }}
            {{ form_row(form.content) }}
            {{ form_row(form._token) }}
            {% if is_granted('ROLE_ADMIN') %}
                {{ form_row(form.assignedTo, { 'label': 'Assigné à:' }) }}
            {% endif %}

            <p>Auteur : {{ task.user }}</p>


            <button type="submit" class="btn btn-success pull-right m-2">Modifier</button>
            <a href="{{ path('task_list') }}" class="btn btn-primary">Retour à la liste des tâches</a>
        </section>

        <div id="divCheckbox" style="display: none;">
            {{ form_rest(form) }}

        </div>



    </div>
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block header_title %}
    {{ include('task/_header.html.twig') }}
{% endblock %}

{% block body %}

    <div class="container pb-5">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header-tab card-header justify-content-between">
                    <div class="card-header-title font-size-lg text-capitalize font-weight-normal"><i
                                class="fa fa-tasks"></i>&nbsp;Liste des Tâches ({{ tasks.getTotalItemCount }})
                    </div>
                    <div class="list-group-horizontal">

                        <a class="btn {% if btn == 'btnAll' %}  btn-primary {% else %} btn-outline-primary{% endif %}"
                           href="{{ path('task_list') }}"><i class="fas fa-list-ul"></i>
                            <span class="status-label">
                                Tout
                            </span>
                        </a>

                        <a class="btn {% if btn == 'btnTodo' %} btn-danger {% else %} btn-outline-danger{% endif %}"
                           href="{{ path('task_list_todo') }}" id="todo"><i class="fas fa-times-circle"></i>
                            <span class="status-label">
                            Todo
                            </span>
                        </a>


                        <a class="btn {% if btn == 'btnInProgress' %} btn-warning {% else %} btn-outline-warning{% endif %}"
                           href="{{ path('task_list_progress') }}"><i class="fas fa-spinner"></i>
                            <span class="status-label">
                            In Progress
                            </span>
                        </a>

                        <a class="btn {% if btn == 'btnDone' %} btn-success {% else %} btn-outline-success{% endif %}"
                           href="{{ path('task_list_done') }}"><i class="fa fa-check"></i>
                            <span class="status-label">
                            Done
                            </span>
                        </a>

                    </div>
                </div>
                {{ include('task/_task.html.twig') }}
                <div class="d-block card-footer d-inline-flex justify-content-between">
                    <div class="navigation">
                        {{ knp_pagination_render(tasks) }}
                    </div>
                    <div class="text-right">
                        <a href="{{ path('task_create') }}">
                            <button class="btn btn-primary">Ajouter une tâche</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('assign') }}
{% endblock %}